// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TwitterCloneApi.Models;

public partial class Country
{
    public int Id { get; set; }

    public string Country1 { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}