// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TwitterCloneApi.Models;

public partial class Tweet
{
    public int Id { get; set; }

    public int IdUser { get; set; }

    public string Content { get; set; }

    public DateTime PublishDatetime { get; set; }

    public bool IsPublic { get; set; }

    public virtual User IdUserNavigation { get; set; }
}