// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TwitterCloneApi.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public int IdCountry { get; set; }

    public bool IsActive { get; set; }

    public virtual Country IdCountryNavigation { get; set; }

    public virtual ICollection<Tweet> Tweets { get; set; } = new List<Tweet>();
}